name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            vpc:
              - 'vpc/**'

      - name: Configure AWS credentials
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform init

      - name: Terraform Plan
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform plan -input=false -var-file=terraform.tfvars

      - name: Await Manual Approval
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        environment: terraform-approval
        run: echo "Manual approval granted to proceed with selected action"

      - name: Terraform Apply or Destroy
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -input=false -var-file=terraform.tfvars
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -input=false -var-file=terraform.tfvars
          else
            echo "Invalid action selected"; exit 1
          fi

  sg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            sg:
              - 'sg/**'

      - name: Configure AWS credentials
        if: ${{ steps.changes.outputs.sg == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        if: ${{ steps.changes.outputs.sg == 'true' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        if: ${{ steps.changes.outputs.sg == 'true' }}
        working-directory: ./sg
        run: terraform init

      - name: Terraform Plan
        if: ${{ steps.changes.outputs.sg == 'true' }}
        working-directory: ./sg
        run: terraform plan -input=false -var-file=terraform.tfvars

      - name: Await Manual Approval
        if: ${{ steps.changes.outputs.sg == 'true' }}
        environment: terraform-approval
        run: echo "Manual approval granted to proceed with selected action"

      - name: Terraform Apply or Destroy
        if: ${{ steps.changes.outputs.sg == 'true' }}
        working-directory: ./sg
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -input=false -var-file=terraform.tfvars
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -input=false -var-file=terraform.tfvars
          else
            echo "Invalid action selected"; exit 1
          fi

  ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ec2:
              - 'ec2/**'

      - name: Configure AWS credentials
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        working-directory: ./ec2
        run: terraform init

      - name: Terraform Plan
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        working-directory: ./ec2
        run: terraform plan -input=false -var-file=terraform.tfvars

      - name: Await Manual Approval
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        environment: terraform-approval
        run: echo "Manual approval granted to proceed with selected action"

      - name: Terraform Apply or Destroy
        if: ${{ steps.changes.outputs.ec2 == 'true' }}
        working-directory: ./ec2
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -input=false -var-file=terraform.tfvars
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -input=false -var-file=terraform.tfvars
          else
            echo "Invalid action selected"; exit 1
          fi
