name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'vpc/**'
      - 'sg-ec2/**'

permissions:
  id-token: write
  contents: read

jobs:
  vpc:
    if: contains(github.event.head_commit.message, 'vpc') || github.event_name == 'push' && contains(join(github.event.commits.*.modified), 'vpc/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: vpc
        run: terraform init

      - name: Terraform Plan
        working-directory: vpc
        run: terraform plan -var-file=dev.tfvars -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: vpc
        run: terraform apply -var-file=dev.tfvars -auto-approve -input=false

  sg:
    if: contains(github.event.head_commit.message, 'sg-ec2') || github.event_name == 'push' && contains(join(github.event.commits.*.modified), 'sg-ec2/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: sg-ec2
        run: terraform init

      - name: Terraform Plan
        working-directory: sg-ec2
        run: terraform plan -var-file=dev.tfvars -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: sg-ec2
        run: terraform apply -var-file=dev.tfvars -auto-approve -input=false
