name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  pull_request:

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required for checkout

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials using OIDC + Secret
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          #aws-region: ap-south-1   # change to your AWS region

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8   # or your preferred version

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan with dev.tfvars
      - name: Terraform Plan
        run: terraform plan -input=false -var-file=dev.tfvars

      # Step 6: Terraform Apply with dev.tfvars (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -var-file=dev.tfvars
