name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  vpc:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: changes changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            vpc:
              - 'vpc/**'

      - name: Terraform Init
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform init

      - name: Terraform Format
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform fmt -recursive

      - name: Terraform Validate
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform validate

      - name: Terraform Plan
        if: ${{ steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform plan -input=false -var-file=terraform.tfvars

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && steps.changes.outputs.vpc == 'true' }}
        working-directory: ./vpc
        run: terraform apply -input=false -var-file=terraform.tfvars -auto-approve

  sg:
    ru
